### ISSUE TITLE
FrontEnd - 유저 이름 검색 및 분석 페이지

### ISSUE THREAD

**Issue by 2hongbi** [data-engineering-team4/Lulu#53]
## 상세 내용

특정 유저의 챔피언 숙련도와 추천 챔피언을 검색하고 분석하는 페이지입니다.

## 예상 소요 시간
- [ ] `0.5h`
- [ ] `1h`
- [ ] `1.5h`
- [ ] `2h`
- [ ] `2.5h`
- [ ] `3h`
- [x] `기타(예상시간)`

## Example code
```python
가능한 경우 여기에 몇 가지 예제 코드를 입력해주세요.
```

## Error log

```
에러 로그가 있다면 여기에 입력해주세요.
```

**Comment by fluencygod** [comment]
밴픽 페이지로 통합하기로 결정해서 close 했습니다.
